apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-checker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-checker
  template:
    metadata:
      labels:
        app: password-checker
    spec:
      containers:
      - name: password-checker
        image: sivanandhini23/password-checker:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: password-checker-service
spec:
  selector:
    app: password-checker
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    nodePort: 30092
