pipeline {
    agent any

    environment {
        IMAGE_NAME = 'password-checker-app'
    }

    stages {
        stage('Install Dependencies') {
    steps {
        sh 'sudo pip install pyinstaller fastapi uvicorn pydantic black flake8 pylint'
    }
}

       stage('Run Unit Tests') {
    steps {
        sh 'export PYTHONPATH=$PYTHONPATH:/var/jenkins_home/workspace/Password_Checker_Pipeline/DOCKER_ARTIFACTORY && python3 -m unittest discover -s /var/jenkins_home/workspace/Password_Checker_Pipeline/DOCKER_ARTIFACTORY/tests -p "test_*.py"'
    }
}


        stage('Linting & Formatting') {
            steps {
                sh 'black --check lib/ tests/ || true'
                sh 'flake8 lib/ tests/ || true'
                sh 'pylint lib/*.py || true'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8099:8081 $IMAGE_NAME'
            }
        }
    }
}
