pipeline {
    agent any

    environment {
        IMAGE_NAME = 'password-checker-app'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh '''
                    pip3 install pyinstaller fastapi uvicorn pydantic
                '''
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh '''
                    python3 -m unittest discover -s ./DOCKER_ARTIFACTORY/tests -p "test_*.py"
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8099:8081 $IMAGE_NAME'
            }
        }
    }
}
