pipeline {
    agent any

    environment {
        VENV_PATH = "${WORKSPACE}/venv/bin"
        PATH = "${VENV_PATH}:${env.PATH}"
    }

    stages {
        stage('Setup Virtualenv & Install Dependencies') {
            steps {
                script {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install pyinstaller
                        pip install fastapi
                        pip install uvicorn
                        pip install pydantic
                    '''
                }
            }
        }

        stage('Build Package') {
            steps {
                script {
                    sh '''
                        . venv/bin/activate
                        pwd  # Print the working directory to ensure you're in the correct path
                        pyinstaller -y JENKINS_PIPELINE/src/main.py --distpath bin --name password_checker --paths=lib  
                    '''
                }
            }
        }

        stage('Archive') {
            steps {
                script {
                    archiveArtifacts artifacts: 'bin/**', fingerprint: true  
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
