pipeline {
    agent any

    environment {
        VENV_PATH = "${WORKSPACE}/venv/bin"
        PATH = "${VENV_PATH}:${env.PATH}"
    }

    stages {
        stage('Setup Virtualenv & Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install pyinstaller
                '''
            }
        }

        stage('Build Package') {
            steps {
                sh '''
                    . venv/bin/activate
                    echo "Current Directory: $(pwd)"
                    echo "List files:"
                    ls -R
                    pyinstaller --onefile JENKINS_PIPELINE/src/main.py --name password_checker
                    echo "Build output:"
                    ls -l dist/
                '''
            }
        }

        stage('Archive') {
            steps {
                sh 'ls -l dist/'
                archiveArtifacts artifacts: 'dist/password_checker', fingerprint: true
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
